import type { Metadata } from "next";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    if (!session || !session?.user.id) {
        redirect(`/login`);
    }

    return (
        <div className="dark:bg-black bg-white mt-14">
            {children}
        </div>
    )
}
